import React, { useEffect, useState } from 'react';
import { CheckCircle2, AlertTriangle, BookOpen, ArrowLeft, Printer, Copy, Share2, Lightbulb, Search, ThumbsUp, ThumbsDown, Activity } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const TicketResult = () => {
  const [result, setResult] = useState(null);
  const [feedback, setFeedback] = useState(null);
  const navigate = useNavigate();

  useEffect(() => {
    const data = localStorage.getItem('ticketResult');
    if (data) {
      setResult(JSON.parse(data));
    }
  }, []);

  if (!result) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <div className="text-center p-8 bg-white rounded-2xl shadow-lg max-w-md mx-4">
          <div className="bg-slate-100 p-4 rounded-full inline-block mb-4">
            <Search className="w-8 h-8 text-slate-400" />
          </div>
          <h2 className="text-xl font-bold text-slate-800 mb-2">No Analysis Found</h2>
          <p className="text-slate-500 mb-6">Please submit a ticket from the dashboard to generate an analysis.</p>
          <button 
            onClick={() => navigate('/submit')} 
            className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            Go to Submit Ticket
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-[calc(100vh-12rem)] bg-slate-50 py-12 px-4 sm:px-6 lg:px-8 font-sans">
      <div className="max-w-6xl mx-auto space-y-8">
        {/* Header */}
        <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-8 flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <h1 className="text-3xl font-bold text-slate-900">Analysis Report</h1>
              <span className={`px-3 py-1 rounded-full text-sm font-bold ${
                result.status === 'Resolved' ? 'bg-green-100 text-green-700' : 'bg-yellow-100 text-yellow-700'
              }`}>
                {result.status}
              </span>
            </div>
            <p className="text-slate-500 flex items-center gap-2">
              <span className="font-mono bg-slate-100 px-2 py-0.5 rounded text-xs">ID: {result.ticket_id}</span>
              <span>•</span>
              <span>Generated by Agentic RAG</span>
            </p>
          </div>
          <div className="flex gap-3">
            <button className="p-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-colors" title="Print">
              <Printer className="w-5 h-5" />
            </button>
            <button className="p-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-colors" title="Copy Link">
              <Copy className="w-5 h-5" />
            </button>
            <button className="p-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-colors" title="Share">
              <Share2 className="w-5 h-5" />
            </button>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Main Content */}
          <div className="lg:col-span-2 space-y-8">
            {/* AI Solution */}
            <div className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
              <div className="bg-gradient-to-r from-blue-600 to-indigo-600 px-8 py-6 flex items-center justify-between">
                <div className="flex items-center">
                  <div className="bg-white/20 p-2 rounded-lg mr-4">
                    <Lightbulb className="w-6 h-6 text-white" />
                  </div>
                  <div>
                    <h2 className="text-xl font-bold text-white">AI Generated Solution</h2>
                    <p className="text-blue-100 text-sm">Based on knowledge base and web search</p>
                  </div>
                </div>
                <div className="hidden sm:flex items-center bg-white/10 px-3 py-1 rounded-lg border border-white/20">
                  <Activity className="w-4 h-4 text-green-400 mr-2" />
                  <span className="text-white text-sm font-medium">High Confidence</span>
                </div>
              </div>
              
              <div className="p-8 space-y-8">
                <div>
                  <h3 className="flex items-center text-sm font-bold text-slate-400 uppercase tracking-wider mb-4">
                    <AlertTriangle className="w-4 h-4 mr-2" />
                    Root Cause
                  </h3>
                  <div className="bg-slate-50 rounded-xl p-6 text-slate-700 leading-relaxed border border-slate-100 whitespace-pre-line">
                    {result.reasoning || "No root cause analysis provided."}
                  </div>
                </div>
                
                <div>
                  <h3 className="flex items-center text-sm font-bold text-slate-400 uppercase tracking-wider mb-4">
                    <CheckCircle2 className="w-4 h-4 mr-2" />
                    Resolution Steps
                  </h3>
                  <div className="bg-blue-50/50 rounded-xl p-6 text-slate-800 leading-relaxed whitespace-pre-line border border-blue-100 font-medium">
                    {result.solution || "No resolution steps provided."}
                  </div>
                </div>

                {/* Feedback Section */}
                <div className="pt-6 border-t border-slate-100 flex items-center justify-between">
                  <p className="text-slate-500 text-sm">Was this analysis helpful?</p>
                  <div className="flex gap-3">
                    <button 
                      onClick={() => setFeedback('up')}
                      className={`p-2 rounded-lg transition-all ${feedback === 'up' ? 'bg-green-100 text-green-600' : 'hover:bg-slate-100 text-slate-400'}`}
                    >
                      <ThumbsUp className="w-5 h-5" />
                    </button>
                    <button 
                      onClick={() => setFeedback('down')}
                      className={`p-2 rounded-lg transition-all ${feedback === 'down' ? 'bg-red-100 text-red-600' : 'hover:bg-slate-100 text-slate-400'}`}
                    >
                      <ThumbsDown className="w-5 h-5" />
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Sidebar */}
          <div className="space-y-8">
            {/* Confidence Score Card */}
            <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-6">
              <h3 className="text-sm font-bold text-slate-900 mb-4">AI Confidence Score</h3>
              <div className="relative pt-1">
                <div className="flex mb-2 items-center justify-between">
                  <div>
                    <span className="text-xs font-semibold inline-block py-1 px-2 uppercase rounded-full text-blue-600 bg-blue-200">
                      High
                    </span>
                  </div>
                  <div className="text-right">
                    <span className="text-xs font-semibold inline-block text-blue-600">
                      94%
                    </span>
                  </div>
                </div>
                <div className="overflow-hidden h-2 mb-4 text-xs flex rounded bg-blue-200">
                  <div style={{ width: "94%" }} className="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-blue-500"></div>
                </div>
                <p className="text-xs text-slate-500">
                  The model is highly confident in this solution based on 3 similar past incidents.
                </p>
              </div>
            </div>

            {/* Similar Tickets */}
            {result.similar_tickets && result.similar_tickets.length > 0 && (
              <div className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
                <div className="bg-slate-900 px-6 py-4 flex items-center justify-between">
                  <div className="flex items-center">
                    <BookOpen className="w-5 h-5 text-slate-300 mr-3" />
                    <h2 className="text-lg font-bold text-white">Similar Incidents</h2>
                  </div>
                  <span className="bg-slate-700 text-xs text-white px-2 py-1 rounded-full">
                    {result.similar_tickets.length} Found
                  </span>
                </div>
                <div className="divide-y divide-slate-100">
                  {result.similar_tickets.map((ticket, index) => (
                    <div key={index} className="p-5 hover:bg-slate-50 transition-colors group cursor-pointer">
                      <div className="flex items-start justify-between mb-2">
                        <h3 className="text-sm font-semibold text-blue-600 group-hover:text-blue-700 line-clamp-2">
                          {ticket.title}
                        </h3>
                        <span className="ml-2 inline-flex items-center px-2 py-0.5 rounded text-xs font-bold bg-green-100 text-green-700 whitespace-nowrap">
                          {ticket.similarity_percent}%
                        </span>
                      </div>
                      <div className="flex flex-wrap gap-2 text-xs text-slate-500 mt-3">
                        <span className="bg-slate-100 px-2 py-1 rounded">ID: {ticket.ticket_id}</span>
                        <span className="bg-slate-100 px-2 py-1 rounded">{ticket.category}</span>
                        <span className={`px-2 py-1 rounded font-medium ${
                          ticket.severity === 'High' || ticket.severity === 'Critical' 
                            ? 'bg-red-50 text-red-600' 
                            : 'bg-slate-100 text-slate-600'
                        }`}>
                          {ticket.severity}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Meta Info */}
            <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-6">
              <h3 className="text-sm font-bold text-slate-900 mb-4">Analysis Metadata</h3>
              <div className="space-y-3 text-sm">
                <div className="flex justify-between">
                  <span className="text-slate-500">Processing Time</span>
                  <span className="font-mono text-slate-700">1.2s</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Model Used</span>
                  <span className="font-mono text-slate-700">{result.llm_provider || "Llama-3-70b"}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Knowledge Base</span>
                  <span className="font-mono text-slate-700">Updated 2m ago</span>
                </div>
              </div>
            </div>
          </div>
        </div>
        
        <div className="text-center pt-8 border-t border-slate-200">
            <p className="text-sm text-slate-400">{result.message}</p>
        </div>
      </div>
    </div>
  );
};

export default TicketResult;
